#!/usr/bin/env python
'''
Created on Sep 24, 2013

@author: Grant Hoffman
@email: grantleehoffman@gmail.com
github: github.com/grantleehoffman/BGDeploy

'''
import argparse, sys, os, inspect
#Find package paths from arguments script
cmd_folder = os.path.realpath(os.path.abspath(os.path.split(inspect.getfile(inspect.currentframe()))[0]))
if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)
cmd_subfolder = os.path.realpath(os.path.abspath(os.path.join(os.path.split(inspect.getfile(inspect.currentframe()))[0], "project")))
if cmd_subfolder not in sys.path:
    sys.path.insert(0, cmd_subfolder)

# Python2.7 expected:
if sys.version_info[0] != 2 or sys.version_info[1] < 7:
    sys.exit('This program needs Python2.7+')

#Argument parsing for CLI
desc = """Blue Green deployment automation through Route53 updates"""
parser = argparse.ArgumentParser(description=desc, version='1.0', formatter_class=argparse.ArgumentDefaultsHelpFormatter)

parser.add_argument('-e', '--elbname',
                    help='elb name',
                    dest='currentelbname',
                    action='store',
                    default=None,
                    )
parser.add_argument('-u', '--elbupdate',
                    help='elb name to add to record alias',
                    dest='updateelbname',
                    action='store',
                    default=None,
                    )
parser.add_argument('-z', '--zone',
                    help='Route53 hosted domain zone',
                    dest='dnszone',
                    required='true',
                    action='store',
                    )
parser.add_argument('-n', '--recordname',
                    help='record name to update',
                    dest='recordname',
                    required='true',
                    action='store',
                    )
parser.add_argument('-t', '--type',
                    help='record typ',
                    dest='recordtype',
                    action='store',
                    default='A',
                    )
parser.add_argument('-r', '--region',
                    help='AWS region',
                    dest='region',
                    action='store',
                    default='us-east-1',
                    )
parser.add_argument('-l', '--ttl',
                    help='time to live number',
                    dest='ttl',
                    action='store',
                    default='30',
                    )
parser.add_argument("--create-only", 
                    help='Create a new Record entry in the zone', 
                    dest='create', 
                    action="store_true")

args = parser.parse_args()

#Arg Variables
recordname = args.recordname    
recordtype = args.recordtype
ttl = args.ttl
DNSZone = args.dnszone
region = args.region
update_elbname = args.updateelbname
currentelbname = args.currentelbname
create = args.create


if __name__ == '__main__':
    from project.namerecord import namerecord
    #Run create or update job
    if create:
        record = namerecord(recordname, recordtype, ttl, DNSZone, region, update_elbname)
        record.create()
    else:
        #Create namerecord object, and run update
        new = namerecord(recordname, recordtype, ttl, DNSZone, region, update_elbname, currentelbname)
        new.update()
    

    

    
